# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 864f5a73589093d0e583cf31bd76fd08a4ff6ebc8a12a2b56485924de88d63805a5e4dc67acfeb8124a6528a63032eacf8a294c3eb6f2a3334644c20440ac51e

test:
  secret_key_base: de3c556e41e8a7203678370e89c832dd13f25a2d31c88e3f3397909646956f3306b53f388b927be0c6ac0241fc0c512ec0d1e02fa7561ee2246d5256e7af61bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
